### ISSUE TITLE
Collection not filtering integer field

### ISSUE THREAD

**Issue by rodfersou** [plone/plone.app.querystring#32]
I have an integer field and when I try to create a filter on it it didn't work.

Looking at p.a.querystring code I see that the related operators don't work:
* plone.app.querystring.operation.int.is
* plone.app.querystring.operation.int.lessThan
* plone.app.querystring.operation.int.largerThan

They are mapped to these methods respectively:
* [plone.app.querystring.queryparser._equal](https://github.com/plone/plone.app.querystring/blob/1052e94636eaf750c747d619c730adaf45ef2082/plone/app/querystring/queryparser.py#L64)
* [plone.app.querystring.queryparser._lessThan](https://github.com/plone/plone.app.querystring/blob/1052e94636eaf750c747d619c730adaf45ef2082/plone/app/querystring/queryparser.py#L96)
* [plone.app.querystring.queryparser._largerThan](https://github.com/plone/plone.app.querystring/blob/1052e94636eaf750c747d619c730adaf45ef2082/plone/app/querystring/queryparser.py#L86)

And these methods don't convert the value to int (because they are used for other string based types).

Also I tested the plone.app.querystring.operation.selection.is and it fail too with an int field.

Looking at the [tests of these methods](https://github.com/plone/plone.app.querystring/blob/1052e94636eaf750c747d619c730adaf45ef2082/plone/app/querystring/tests/testQueryParser.py#L247), you clearly see that it is not testing every kind of data.

My suggestions are to create new methods just for int fields (doing type cast) and to add a new operator for int fields plone.app.querystring.operation.intselection.is (something like this)

**Comment by MrTango** [comment]
Applies that for Plone 5 or 4 or both?

**Comment by hvelarde** [comment]
both

**Comment by jensens** [comment]
closed by merging #33 and #34
