### ISSUE TITLE
folder_contents empty for folder with same id as portal

### ISSUE THREAD

**Issue by cillianderoiste** [plone/plone.app.querystring#79]
To reproduce (Plone 5.1b3):

* Create a portal with id "plone"
* Create a folder in it with the id "plone-an-introduction"
* Viewing folder_contents on plone/plone-an-introduction shows no content

This happens here: https://github.com/plone/plone.app.querystring/blob/1.4.4/plone/app/querystring/queryparser.py#L290 since it checks if the start of the path is the same as the portal root.

I wonder why it checks the start, in my case I have values = u'/plone-an-introduction' and row = '/plone' so we could check if values == row, although that would still fail in the case where the folder has the id 'plone'.

Is this the right place to fix the issue? This code gets called from here: https://github.com/plone/plone.app.vocabularies/blob/master/plone/app/vocabularies/catalog.py#L615

**Comment by eikichi18** [comment]
+1

**Comment by arsenico13** [comment]
+1
