### ISSUE TITLE
Management of "negative" queries with "not" 

### ISSUE THREAD

**Issue by sgeulette** [plone/plone.app.querystring#88]
Hi,
Since [Products.ZCatalog >= 3.0](https://pypi.python.org/pypi/Products.ZCatalog/4.1#a1-2012-04-22), it's possible to query with parameters like {'index': {'not': ['a', 'b']}}.

It would be great to have negative operator on collections: like "IsNot", "DoesntContains", etc.

Regards

**Comment by CharString** [comment]
That's a good start. But with the current front end for Collections, we should be able to do proper Conjunctive Normal Form. Or ideally, let us pick DNF if that fits our brain better. Full CNF or DNF support would unlock the power of a few centuries of set theory and boolean logic.

**Comment by djay** [comment]
> That's a good start. But with the current front end for Collections, we should be able to do proper Conjunctive Normal Form. Or ideally, let us pick DNF if that fits our brain better. Full CNF or DNF support would unlock the power of a few centuries of set theory and boolean logic.

It supports what the index supports. if you want it you might want to start work on a PR to ZCatalog. Keep in mind google search doesn't support CNF.

**Comment by CharString** [comment]
> Keep in mind google search doesn't support CNF.

How does google search tie into this?

**Comment by jensens** [comment]
this was fixed in 1.6.0
